#!/usr/bin/env python3
"""Build notebooks/23_structural_window_crossings.ipynb in the repo's style."""

import json

NB_PATH = "/home/alexmy/SGS/SGS_lib/fractal_manifold_gen2/ewm-laya-bonsai-lab/notebooks/08_structural_window_crossings.ipynb"

md = lambda s: {"cell_type": "markdown", "metadata": {}, "source": s}
code = lambda s: {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": s,
}

cells = [
    md(
        "# 08 — Multi-window structural state: moving averages + crossovers\n"
        "\n"
        "The structural-router and distillation notebooks (ewm-state-machine 21–22) give the router a **single-step** structural reading\n"
        "(bss, D/R/N, ring). This notebook mimics a **moving-average view**: the\n"
        "state now also carries the structural series' moving averages over the\n"
        "last 2/3/4/5 steps, plus **crossover events** where a short window\n"
        "crosses a long window from below (`..._up`) or from above (`..._down`)\n"
        "— the same idea as fast/slow MA crosses, but over the HLLSet\n"
        "trajectory (cf. the `ewm-scene ma` fast/slow BSSτ windows).\n"
        "\n"
        "Plan:\n"
        "\n"
        "1. run the prompted teacher with the extended state and check whether\n"
        "   the window/crossover context changes its decisions,\n"
        "2. visualise the fast/slow MAs and their crossings,\n"
        "3. train the typed head on the extended structural features (still no\n"
        "   query identity) and compare against the distillation notebook's structural-only\n"
        "   baseline (67% holdout).\n"
        "\n"
        "The loop-side machinery is `_structural_state` in `trainer/loop.py`;\n"
        "the prompted router renders the new fields in `structural_decision_prompt`."
    ),
    code(
        "import os, sys, json\n"
        "\n"
        "# Same GPU pin as notebooks 21–22: with PCI_BUS_ID on this machine the\n"
        "# Quadro M1200 is device 0 and the RTX 3060 is device 1.\n"
        "os.environ[\"CUDA_DEVICE_ORDER\"] = \"PCI_BUS_ID\"\n"
        "os.environ[\"CUDA_VISIBLE_DEVICES\"] = \"1\"\n"
        "os.environ.setdefault(\"HF_HUB_DISABLE_PROGRESS_BARS\", \"1\")\n"
        "\n"
        "import numpy as np\n"
        "import torch\n"
        "import torch.nn as nn\n"
        "\n"
        "EWM_SM = \"/home/alexmy/SGS/SGS_lib/fractal_manifold_gen2/ewm-state-machine\"\n"
        "sys.path.insert(0, EWM_SM)\n"
        "\n"
        "from trainer import (\n"
        "    DecisionRecord,\n"
        "    DecisionRouter,\n"
        "    EwmScene,\n"
        "    JevAdapter,\n"
        "    LlmAdapter,\n"
        "    StructuralLlmRouter,\n"
        "    run_open_loop,\n"
        "    run_jev_loop,\n"
        ")\n"
        "\n"
        "WORK = \"/home/alexmy/.cache/ewm-window-crossings\"\n"
        "os.makedirs(WORK, exist_ok=True)\n"
        "ewm = EwmScene()\n"
        "print(\"torch sees:\", torch.cuda.get_device_name(0),\n"
        "      round(torch.cuda.get_device_properties(0).total_memory / 1e9, 1), \"GB\")\n"
        "print(\"work:\", WORK)"
    ),
    code(
        "QUERIES = [\n"
        "    \"What is the capital of France?\",\n"
        "    \"Explain the intuition behind general relativity in three sentences.\",\n"
        "    \"Write a haiku about rain.\",\n"
        "    \"What is 17 * 24?\",\n"
        "    \"Compare supervised and unsupervised learning briefly.\",\n"
        "    \"What is the speed of light?\",\n"
        "    \"Define entropy in simple words.\",\n"
        "    \"Summarize the plot of Romeo and Juliet.\",\n"
        "]\n"
        "\n"
        "adapter = LlmAdapter(max_new_tokens=32)\n"
        "teacher = StructuralLlmRouter(max_new_tokens=128)   # prompt is longer now\n"
        "jev     = JevAdapter(mock=True)\n"
        "\n"
        "print(\"adapter names:\", adapter.names)\n"
        "print(\"teacher mode:\", \"mock\" if teacher.mock else \"real\", \"|\", teacher.model_id)"
    ),
    md("## §1 — Extended-state teacher loop (windows + crossings in the prompt)"),
    code(
        "open_result = run_open_loop(adapter, ewm, QUERIES, WORK, cycles=2, max_new_tokens=32)\n"
        "print(\"IICA:\", open_result.same_union, \"| BSS:\", open_result.M_ol.shape,\n"
        "      \"| period:\", open_result.period, \"(true 8)\")"
    ),
    code(
        "teacher_result = run_jev_loop(\n"
        "    adapter, teacher, ewm, open_result, QUERIES, WORK, T=24, max_new_tokens=32,\n"
        "    structural=True, ingest_decision=True,\n"
        ")\n"
        "data = teacher_result.routing_log\n"
        "print()\n"
        "print(\"teacher decision distribution:\")\n"
        "for n in adapter.names:\n"
        "    print(f\"  {n:6s} {sum(1 for r in data if r['decision']['decision'] == n):2d} steps\")\n"
        "\n"
        "# show the extended state the router saw at a late step\n"
        "late = data[-1]\n"
        "print()\n"
        "print(\"late-state keys:\", sorted(late[\"state\"].keys()))\n"
        "print(\"windows (first 6):\", dict(list((late[\"state\"].get(\"windows\") or {}).items())[:6]))\n"
        "cross = late[\"state\"].get(\"crossings\") or {}\n"
        "print(\"crossings (true events):\", sorted(k for k, v in cross.items() if v))\n"
        "\n"
        "with open(f\"{WORK}/window_dataset.jsonl\", \"w\") as fh:\n"
        "    for r in data:\n"
        "        fh.write(json.dumps(r) + \"\\n\")\n"
        "print(\"saved:\", f\"{WORK}/window_dataset.jsonl\", f\"({len(data)} labelled states)\")"
    ),
    md("## §2 — Did the window/crossover context change the teacher?"),
    code(
        "# Per-step view: query -> decision, plus how many crossover events were\n"
        "# live at that step (a proxy for 'the state was structurally active').\n"
        "print(f\"{'step':>4s} {'q':>2s} {'decision':>8s} {'crossings':>10s}  query\")\n"
        "for r in data:\n"
        "    st = r[\"state\"]\n"
        "    cross = st.get(\"crossings\") or {}\n"
        "    n_cross = sum(1 for v in cross.values() if v)\n"
        "    q = st.get(\"query\", \"\")[:38]\n"
        "    print(f\"{r['step']:4d} {r['step'] % 8:2d} {r['decision']['decision']:>8s} \"\n"
        "          f\"{n_cross:10d}  {q}\")\n"
        "\n"
        "# nb22's policy was: q=1 -> llm_b, everything else -> llm_c.\n"
        "nb22_policy = {1: \"llm_b\"}\n"
        "changed = sum(1 for r in data\n"
        "              if r[\"decision\"][\"decision\"] != nb22_policy.get(r[\"step\"] % 8, \"llm_c\"))\n"
        "print()\n"
        "print(f\"steps where the extended state changed the decision vs the nb22 policy: {changed}/{len(data)}\")"
    ),
    md("## §3 — Fast/slow moving averages and their crossings"),
    code(
        "%matplotlib inline\n"
        "import matplotlib.pyplot as plt\n"
        "\n"
        "# Reconstruct per-step MA series from the routing log (each state carries\n"
        "# its own windows), then mark crossings of MA2 vs MA5.\n"
        "steps = [r[\"step\"] for r in data]\n"
        "w = [r[\"state\"].get(\"windows\") or {} for r in data]\n"
        "\n"
        "def series_of(feat):\n"
        "    return [x.get(f\"{feat}_ma2\", 0.0) for x in w], [x.get(f\"{feat}_ma5\", 0.0) for x in w]\n"
        "\n"
        "fig, axes = plt.subplots(2, 1, figsize=(11, 7), sharex=True)\n"
        "for ax, feat in ((axes[0], \"bss_llm_b\"), (axes[1], \"np\")):\n"
        "    ma2, ma5 = series_of(feat)\n"
        "    ax.plot(steps, ma2, \"o-\", lw=1.0, ms=4, color=\"tab:blue\", label=f\"{feat} MA2\")\n"
        "    ax.plot(steps, ma5, \"s-\", lw=1.0, ms=4, color=\"tab:red\", label=f\"{feat} MA5\")\n"
        "    for t in range(1, len(steps)):\n"
        "        if ma2[t - 1] <= ma5[t - 1] < ma2[t]:\n"
        "            ax.scatter([steps[t]], [ma2[t]], marker=\"^\", s=90, color=\"green\",\n"
        "                       label=\"cross up\" if t == 1 or True else \"\", zorder=5)\n"
        "        if ma2[t - 1] >= ma5[t - 1] > ma2[t]:\n"
        "            ax.scatter([steps[t]], [ma2[t]], marker=\"v\", s=90, color=\"purple\",\n"
        "                       label=\"cross down\" if t == 1 or True else \"\", zorder=5)\n"
        "    ax.set_title(f\"{feat}: fast (MA2) vs slow (MA5) with crossovers\")\n"
        "    ax.legend(fontsize=8)\n"
        "    ax.grid(alpha=0.25)\n"
        "axes[1].set_xlabel(\"step\")\n"
        "plt.tight_layout()\n"
        "plt.savefig(f\"{WORK}/window_crossings.png\", dpi=110)\n"
        "plt.show()"
    ),
    md("## §4 — Typed head on the extended structural features (still no query identity)"),
    code(
        "OPTION_ORDER = sorted(adapter.names)\n"
        "CORE = [\"bss_llm_a\", \"bss_llm_b\", \"bss_llm_c\", \"np\", \"rp\", \"dp\",\n"
        "        \"residual\", \"dim\", \"spill_first\"]\n"
        "\n"
        "def structural_features(state):\n"
        "    bss  = state.get(\"bss\") or {}\n"
        "    drn  = state.get(\"drn\") or {}\n"
        "    ring = state.get(\"ring\") or {}\n"
        "    t = float(state.get(\"step\", 0))\n"
        "    ph = 2.0 * np.pi * t / 8.0\n"
        "    feats = [float(bss.get(n, 0.0)) for n in OPTION_ORDER]\n"
        "    feats += [float(drn.get(\"dp\", 0)), float(drn.get(\"rp\", 0)),\n"
        "              float(drn.get(\"np\", 0)), float(drn.get(\"ind1\", 0)),\n"
        "              float(drn.get(\"ind3\", 0))]\n"
        "    feats += [float(ring.get(\"residual\", 0)), float(ring.get(\"in_span\", False)),\n"
        "              float(ring.get(\"dim\", 0)), float(ring.get(\"rotation_count\", 0)),\n"
        "              float(ring.get(\"spill_first\", 0))]\n"
        "    feats += [np.sin(ph), np.cos(ph), t / 16.0, 1.0]\n"
        "    return np.asarray(feats, dtype=np.float32)\n"
        "\n"
        "def extended_features(state):\n"
        "    \"\"\"structural (17) + MA2/MA5 windows (18) + crossings (36) = 71.\"\"\"\n"
        "    f = list(structural_features(state))\n"
        "    windows = state.get(\"windows\") or {}\n"
        "    crossings = state.get(\"crossings\") or {}\n"
        "    for name in CORE:\n"
        "        f += [float(windows.get(f\"{name}_ma2\", 0.0)),\n"
        "              float(windows.get(f\"{name}_ma5\", 0.0))]\n"
        "    for name in CORE:\n"
        "        for ks, kl in ((2, 4), (3, 5)):\n"
        "            for d in (\"up\", \"down\"):\n"
        "                f.append(1.0 if crossings.get(f\"{name}_x{ks}x{kl}_{d}\", False) else 0.0)\n"
        "    return np.asarray(f, dtype=np.float32)\n"
        "\n"
        "class TypedHead(nn.Module):\n"
        "    def __init__(self, in_dim, n_options, hidden=16, dropout=0.4):\n"
        "        super().__init__()\n"
        "        self.net = nn.Sequential(\n"
        "            nn.Linear(in_dim, hidden), nn.ReLU(), nn.Dropout(dropout),\n"
        "            nn.Linear(hidden, n_options),\n"
        "        )\n"
        "    def forward(self, x):\n"
        "        return self.net(x)\n"
        "\n"
        "def train_head(X, Y, seed=0, epochs=800):\n"
        "    rng = np.random.default_rng(seed)\n"
        "    y_cls = np.argmax(Y, axis=1)\n"
        "    tr, te = [], []\n"
        "    for c in np.unique(y_cls):\n"
        "        idx_c = np.where(y_cls == c)[0]\n"
        "        rng.shuffle(idx_c)\n"
        "        n_tr_c = max(1, int(0.8 * len(idx_c)))\n"
        "        tr += list(idx_c[:n_tr_c]); te += list(idx_c[n_tr_c:])\n"
        "    tr, te = np.array(tr), np.array(te)\n"
        "    mu, sd = X[tr].mean(axis=0), X[tr].std(axis=0) + 1e-9\n"
        "    Xs = (X - mu) / sd\n"
        "    torch.manual_seed(seed)\n"
        "    model = TypedHead(X.shape[1], len(OPTION_ORDER))\n"
        "    opt = torch.optim.Adam(model.parameters(), lr=2e-3, weight_decay=3e-3)\n"
        "    Xtr = torch.tensor(Xs[tr]); Ytr = torch.tensor(Y[tr])\n"
        "    Xte = torch.tensor(Xs[te]); Yte = torch.tensor(Y[te])\n"
        "    for _ in range(epochs):\n"
        "        opt.zero_grad()\n"
        "        logp = torch.log_softmax(model(Xtr), dim=1)\n"
        "        loss = torch.mean(torch.sum(-Ytr * logp, dim=1))\n"
        "        loss.backward()\n"
        "        opt.step()\n"
        "    with torch.no_grad():\n"
        "        p_te = torch.softmax(model(Xte), dim=1).numpy()\n"
        "    acc = float(np.mean(np.argmax(p_te, axis=1) == np.argmax(Y[te], axis=1)))\n"
        "    kl = float(np.mean(np.sum(Y[te] * (np.log(Y[te] + 1e-9) - np.log(p_te + 1e-9)), axis=1)))\n"
        "    return model, mu, sd, te, p_te, acc, kl\n"
        "\n"
        "Y = np.stack([[r[\"decision\"][\"probabilities\"].get(n, 0.0)\n"
        "              for n in OPTION_ORDER] for r in data])\n"
        "\n"
        "X_base = np.stack([structural_features(r[\"state\"]) for r in data])\n"
        "X_ext  = np.stack([extended_features(r[\"state\"]) for r in data])\n"
        "\n"
        "_, _, _, _, _, acc_base, kl_base = train_head(X_base, Y)\n"
        "print(f\"structural-only (nb22 baseline): test argmax-acc {acc_base:.2f} | test KL {kl_base:.4f}\")\n"
        "\n"
        "head_ext, mu_e, sd_e, te_e, p_e, acc_ext, kl_ext = train_head(X_ext, Y)\n"
        "print(f\"+ windows/crossings           : test argmax-acc {acc_ext:.2f} | test KL {kl_ext:.4f}\")\n"
        "\n"
        "print()\n"
        "print(\"held-out teacher vs extended head:\")\n"
        "for i in range(len(te_e)):\n"
        "    print(f\"  state {te_e[i]:2d}: teacher {np.round(Y[te_e[i]], 2)}  head {np.round(p_e[i], 2)}\")"
    ),
    md("## §5 — A/B: extended teacher vs extended head vs Jev-mock"),
    code(
        "class TypedHeadRouter(DecisionRouter):\n"
        "    def __init__(self, model, feature_fn, option_order, mu, sd):\n"
        "        self.model = model\n"
        "        self.feature_fn = feature_fn\n"
        "        self.option_order = list(option_order)\n"
        "        self.mu = mu\n"
        "        self.sd = sd\n"
        "    def route(self, state, options, instructions, extra_noul=None):\n"
        "        x = (self.feature_fn(state) - self.mu) / self.sd\n"
        "        with torch.no_grad():\n"
        "            logits = self.model(torch.tensor(x).unsqueeze(0))[0]\n"
        "        p = torch.softmax(logits, dim=0).numpy()\n"
        "        probs = {n: float(p[i]) for i, n in enumerate(self.option_order)}\n"
        "        decision = max(probs, key=probs.get)\n"
        "        return DecisionRecord(\n"
        "            decision=decision, confidence=float(probs[decision]),\n"
        "            probabilities=probs, decision_type=\"route_query\", aux={},\n"
        "            model=\"typed-head-window\", mock=False,\n"
        "        )\n"
        "\n"
        "head_router = TypedHeadRouter(head_ext, extended_features, OPTION_ORDER, mu_e, sd_e)\n"
        "head_result = run_jev_loop(\n"
        "    adapter, head_router, ewm, open_result, QUERIES, WORK, T=8, max_new_tokens=32,\n"
        "    structural=True, ingest_decision=True,\n"
        ")\n"
        "\n"
        "jev_result = run_jev_loop(\n"
        "    adapter, jev, ewm, open_result, QUERIES, WORK, T=8, max_new_tokens=32,\n"
        "    ingest_decision=True,\n"
        ")\n"
        "\n"
        "rows = [(\"teacher-ext\", teacher_result), (\"typed-head-ext\", head_result), (\"jev-mock\", jev_result)]\n"
        "print(f\"{'router':14s} {'choice distribution':30s} {'gated':>6s} {'mean conf':>10s}\")\n"
        "for label, r in rows:\n"
        "    ds = r.decision_log\n"
        "    dist = \", \".join(f\"{n}:{sum(1 for d in ds if d.decision == n)}\" for n in adapter.names)\n"
        "    print(f\"{label:14s} {dist:30s} {sum(r.gated_log):6d} \"\n"
        "          f\"{float(np.mean([d.confidence for d in ds])):10.4f}\")\n"
        "\n"
        "torch.save({\"model\": head_ext.state_dict(), \"mu\": mu_e, \"sd\": sd_e,\n"
        "            \"option_order\": OPTION_ORDER, \"feature_dim\": X_ext.shape[1]},\n"
        "           f\"{WORK}/typed_head_window.pt\")\n"
        "print(\"saved:\", f\"{WORK}/typed_head_window.pt\")"
    ),
    md(
        "## Summary\n"
        "\n"
        "- The loop now passes a **multi-window moving-average view** of the\n"
        "  structural series (last 2/3/4/5 steps) plus **crossover events**\n"
        "  (short vs long window, from above/below) — `trainer/loop.py:\n"
        "  _structural_state`, rendered by `structural_decision_prompt`.\n"
        "- The prompted teacher's decisions were compared against the distillation notebook's\n"
        "  query-deterministic policy; any changes show where the temporal\n"
        "  context actually moved the teacher.\n"
        "- The typed head was retrained on the extended features **without query\n"
        "  identity** and compared against the distillation notebook's structural-only\n"
        "  baseline (67% holdout) — the honest test of whether the lattice's\n"
        "  temporal structure carries the routing signal.\n"
        "\n"
        "Caveats: 24 labelled states is still a scaffold; crossings are sparse\n"
        "events (most steps have none), so their marginal value needs a much\n"
        "longer trajectory to estimate. The machinery is the deliverable — the\n"
        "window/crossing state is now available to any `DecisionRouter` and to\n"
        "the typed-head feature builder."
    ),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "ewm-nanolm",
            "language": "python",
            "name": "ewm-nanolm",
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.10",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

with open(NB_PATH, "w") as fh:
    json.dump(nb, fh, indent=1)
    fh.write("\n")
print("wrote", NB_PATH, "with", len(cells), "cells")
