#!/usr/bin/env python3
"""Build notebooks/13_lattice_gnn.ipynb — GNN over the growing lattice.

No-pretraining scenario: ~100 documents stream in, the universal lattice
grows, three application profiles build their gates, queries arrive as
prompts converted to encodings and are submitted to the general lattice and
to the issuing profile. Then: does a 2-layer GNN over the BSS graph beat a
flat MLP over structural features at recognizing which profile issued a
query?
"""

import json

NB_PATH = "/home/alexmy/SGS/SGS_lib/fractal_manifold_gen2/ewm-laya-bonsai-lab/notebooks/13_lattice_gnn.ipynb"

md = lambda s: {"cell_type": "markdown", "metadata": {}, "source": s}
code = lambda s: {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": s,
}

cells = [
    md(
        "# 13 — A GNN over the growing lattice: profiles without pretraining\n"
        "\n"
        "The question from the design discussion: is a **specialized GNN over\n"
        "the EWM lattice** worth building? This notebook answers it\n"
        "empirically, in the **no-pretraining scenario**: there is no model\n"
        "at the start. Documents stream in, the universal lattice grows,\n"
        "three application profiles build their gates from their own\n"
        "documents, and then the profiles interact through queries.\n"
        "\n"
        "```text\n"
        "   docs ──► encodings ──► HLLSets ──► general lattice (grows)\n"
        "                             │\n"
        "                             └──► profile gates (grow with their docs)\n"
        "\n"
        "   prompt (profile p) ──► host LLM ──► encodings ──► general lattice\n"
        "                                                    └─► BSS(query, gate_p)\n"
        "```\n"
        "\n"
        "- ~100 documents, ~100 tokens each, from 3 synthetic domains;\n"
        "- 3 profiles (`acme-finance`, `medco-clinical`, `ops-logistics`);\n"
        "- 30 queries (10 per profile) — prompts converted by a simulated\n"
        "  host-LLM encoding step, submitted to the general lattice **and** to\n"
        "  the profile that generated the prompt;\n"
        "- then the ML question: given only **structural features** (bits,\n"
        "  coverage, frequency — never text), can a model recognize which\n"
        "  profile issued a query? **Flat MLP vs a 2-layer GNN** over the BSS\n"
        "  graph.\n"
        "\n"
        "This is the notebook-08 discipline again: the graph earns its place\n"
        "only if it beats the flat structural features on the same split."
    ),
    code(
        "import os, random\n"
        "\n"
        "import mmh3\n"
        "import numpy as np\n"
        "import matplotlib.pyplot as plt\n"
        "\n"
        "import torch\n"
        "import torch.nn as nn\n"
        "import torch.nn.functional as F\n"
        "\n"
        "torch.manual_seed(7)\n"
        "np.random.seed(7)\n"
        "rng = random.Random(42)\n"
        "\n"
        "BITS_PER_REG = 32\n"
        "P = 10          # 1024 registers — the soldered precision\n"
        "\n"
        "def frame_set(tokens, p=P):\n"
        "    \"\"\"G1 ∪ G2 ∪ G3 projection (CHANNEL_SEEDS = [0,1,2]) as a Python bitset.\"\"\"\n"
        "    s = 0\n"
        "    m = 1 << p\n"
        "    for t in tokens:\n"
        "        for seed in (0, 1, 2):\n"
        "            h = mmh3.hash64(t.encode(), seed=seed, signed=False)[0]\n"
        "            reg = h & (m - 1)\n"
        "            rem = h >> p\n"
        "            tz = 31 if rem == 0 else min((rem & -rem).bit_length() - 1, 31)\n"
        "            s |= 1 << (reg * BITS_PER_REG + tz)\n"
        "    return s\n"
        "\n"
        "def bss(a, b):\n"
        "    \"\"\"BSS(a,b) = |a ∩ b| / |b| — the fraction of b covered by a.\"\"\"\n"
        "    pb = b.bit_count()\n"
        "    return (a & b).bit_count() / pb if pb else 0.0\n"
        "\n"
        "PROFILES = [\"acme-finance\", \"medco-clinical\", \"ops-logistics\"]\n"
        "DOMAIN_WORDS = {\n"
        "    \"acme-finance\": [\"market\",\"equity\",\"bond\",\"risk\",\"portfolio\",\"dividend\",\"yield\",\n"
        "                      \"capital\",\"audit\",\"ledger\",\"valuation\",\"liquidity\",\"hedge\",\n"
        "                      \"settlement\",\"margin\",\"revenue\",\"expense\",\"asset\",\"liability\",\n"
        "                      \"deposit\",\"forecast\",\"budget\"],\n"
        "    \"medco-clinical\": [\"patient\",\"trial\",\"dosage\",\"symptom\",\"diagnosis\",\"therapy\",\n"
        "                        \"efficacy\",\"placebo\",\"cohort\",\"regimen\",\"adverse\",\"protocol\",\n"
        "                        \"enrollment\",\"endpoint\",\"biomarker\",\"dose\",\"arm\",\"screening\",\n"
        "                        \"followup\",\"outcome\",\"consent\",\"monitor\"],\n"
        "    \"ops-logistics\": [\"shipment\",\"warehouse\",\"inventory\",\"route\",\"dispatch\",\"carrier\",\n"
        "                       \"pallet\",\"tracking\",\"freight\",\"schedule\",\"capacity\",\"dock\",\n"
        "                       \"fleet\",\"manifest\",\"handling\",\"leadtime\",\"backlog\",\"delivery\",\n"
        "                       \"pickup\",\"transit\",\"cargo\",\"distribution\"],\n"
        "}\n"
        "SHARED = [\"the\",\"of\",\"report\",\"update\",\"review\",\"summary\",\"data\",\"system\",\n"
        "          \"process\",\"request\",\"note\",\"status\",\"daily\",\"weekly\",\"current\",\n"
        "          \"new\",\"open\",\"close\",\"check\",\"record\",\"file\",\"entry\"]\n"
        "\n"
        "PROMPTS = {\n"
        "    \"acme-finance\": [\n"
        "        \"equity exposure report\", \"bond yield forecast update\",\n"
        "        \"quarterly revenue audit summary\", \"portfolio risk review status\",\n"
        "        \"dividend payout note\", \"capital liquidity check\",\n"
        "        \"asset valuation entry\", \"budget forecast process\",\n"
        "        \"margin settlement record\", \"hedge exposure review\"],\n"
        "    \"medco-clinical\": [\n"
        "        \"patient trial enrollment status\", \"dosage regimen review\",\n"
        "        \"symptom diagnosis report\", \"therapy efficacy update\",\n"
        "        \"placebo cohort summary\", \"adverse event record\",\n"
        "        \"protocol amendment note\", \"biomarker screening entry\",\n"
        "        \"followup outcome check\", \"dose escalation review\"],\n"
        "    \"ops-logistics\": [\n"
        "        \"shipment warehouse status\", \"inventory route update\",\n"
        "        \"dispatch carrier report\", \"pallet tracking summary\",\n"
        "        \"freight schedule check\", \"capacity dock note\",\n"
        "        \"fleet manifest entry\", \"leadtime backlog review\",\n"
        "        \"delivery pickup record\", \"cargo transit status\"],\n"
        "}\n"
        "\n"
        "print(\"profiles:\", PROFILES)\n"
        "print(\"domain words per profile:\", {p: len(w) for p, w in DOMAIN_WORDS.items()})\n"
        "print(\"hash parity check (tid0):\", mmh3.hash64(b\"tid0\", seed=0, signed=False)[0])"
    ),
    md(
        "## §1 — No pretraining: the lattice grows, the gates build themselves\n"
        "\n"
        "Documents arrive in a shuffled stream (no curriculum, no pretrained\n"
        "model anywhere). Each document is encoded (the simulated host\n"
        "encoder) into its `G1 ∪ G2 ∪ G3` HLLSet and unioned into the\n"
        "**general lattice**; a document's profile also unions it into that\n"
        "profile's **gate** — the gate is literally the profile's documents\n"
        "so far. The plot is the whole \"training process\": two monotone\n"
        "growth curves, no optimizer."
    ),
    code(
        "N_DOCS = 100\n"
        "\n"
        "doc_tokens = []\n"
        "doc_profile = []\n"
        "for i in range(N_DOCS):\n"
        "    p = PROFILES[i % 3]\n"
        "    n = rng.randint(80, 120)\n"
        "    toks = []\n"
        "    for _ in range(n):\n"
        "        toks.append(rng.choice(DOMAIN_WORDS[p]) if rng.random() < 0.72\n"
        "                     else rng.choice(SHARED))\n"
        "    doc_tokens.append(toks)\n"
        "    doc_profile.append(p)\n"
        "\n"
        "order = list(range(N_DOCS))\n"
        "rng.shuffle(order)\n"
        "\n"
        "lattice = 0\n"
        "gates = {p: 0 for p in PROFILES}\n"
        "doc_sets = []\n"
        "lattice_growth = []\n"
        "gate_growth = {p: [] for p in PROFILES}\n"
        "\n"
        "for idx in order:\n"
        "    p = doc_profile[idx]\n"
        "    s = frame_set(doc_tokens[idx])\n"
        "    doc_sets.append((f\"doc{idx:03d}\", p, s))\n"
        "    lattice |= s\n"
        "    gates[p] |= s\n"
        "    lattice_growth.append(lattice.bit_count())\n"
        "    for pp in PROFILES:\n"
        "        gate_growth[pp].append(gates[pp].bit_count())\n"
        "\n"
        "print(\"general lattice pop:\", lattice.bit_count())\n"
        "print(\"gate pops:\", {p: gates[p].bit_count() for p in PROFILES})\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(10, 5))\n"
        "ax.plot(range(1, N_DOCS + 1), lattice_growth, color=\"black\", lw=2.0, label=\"general lattice\")\n"
        "for p in PROFILES:\n"
        "    ax.plot(range(1, N_DOCS + 1), gate_growth[p], lw=1.2, label=p)\n"
        "ax.set_xlabel(\"documents streamed\")\n"
        "ax.set_ylabel(\"active bits (popcount)\")\n"
        "ax.set_title(\"No pretraining — the lattice and the three profile gates grow from the stream\")\n"
        "ax.legend(fontsize=8)\n"
        "ax.grid(alpha=0.25)\n"
        "plt.tight_layout()\n"
        "plt.savefig(\"/tmp/lattice_growth.png\", dpi=110)\n"
        "plt.show()"
    ),
    md(
        "## §2 — Queries: prompts → encodings → lattice + issuing profile\n"
        "\n"
        "Each profile issues 10 query prompts. The **host LLM** converts a\n"
        "prompt into encodings (simulated here by deterministic tokenization\n"
        "of prompt words). Each query is submitted to the **general lattice**\n"
        "(unioned in — the lattice keeps growing) and to its **issuing\n"
        "profile** (we record the gate coverage `BSS(gate_p, query)`)."
    ),
    code(
        "query_sets = []\n"
        "for p in PROFILES:\n"
        "    for q in range(10):\n"
        "        toks = rng.choice(PROMPTS[p]).split()   # host LLM encoding (simulated)\n"
        "        s = frame_set(toks)\n"
        "        query_sets.append((f\"q_{p}_{q}\", p, s))\n"
        "        lattice |= s                            # submitted to the general lattice\n"
        "\n"
        "print(\"queries:\", len(query_sets), \"| lattice pop after queries:\", lattice.bit_count())\n"
        "print()\n"
        "print(\"sample query routing coordinates (BSS(query, gate) per profile):\")\n"
        "for label, p, s in query_sets[:9]:\n"
        "    cov = {pp: round(bss(gates[pp], s), 3) for pp in PROFILES}\n"
        "    print(f\"  {label:16s} issued by {p:14s} -> {cov}\")"
    ),
    md(
        "## §3 — The lattice graph\n"
        "\n"
        "Nodes = 100 documents + 30 queries + 3 gates + the cumulative lattice\n"
        "(the gates/lattice are context nodes — they carry no label, but they\n"
        "anchor the graph). Edges = the **symmetric BSS**\n"
        "`(BSS(i,j)+BSS(j,i))/2` between every pair. This is the graph the\n"
        "GNN will read; the heatmap shows the block structure that the\n"
        "profiles create *without anyone asking for it*."
    ),
    code(
        "nodes = []          # (label, profile_or_None, bitset)\n"
        "nodes += [(l, p, s) for l, p, s in doc_sets]\n"
        "nodes += [(l, p, s) for l, p, s in query_sets]\n"
        "for p in PROFILES:\n"
        "    nodes.append((f\"gate:{p}\", None, gates[p]))\n"
        "nodes.append((\"lattice\", None, lattice))\n"
        "\n"
        "n = len(nodes)\n"
        "labels = [nd[0] for nd in nodes]\n"
        "y = np.array([PROFILES.index(nd[1]) if nd[1] is not None else -1 for nd in nodes])\n"
        "\n"
        "A = np.zeros((n, n))\n"
        "for i in range(n):\n"
        "    for j in range(i, n):\n"
        "        w = (bss(nodes[i][2], nodes[j][2]) + bss(nodes[j][2], nodes[i][2])) / 2\n"
        "        A[i, j] = w\n"
        "        A[j, i] = w\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(9, 8))\n"
        "im = ax.imshow(A, cmap=\"magma\", vmin=0, vmax=0.6)\n"
        "ax.set_title(\"Symmetric BSS adjacency — the lattice graph the GNN reads\")\n"
        "ax.set_xlabel(\"node\")\n"
        "ax.set_ylabel(\"node\")\n"
        "plt.colorbar(im, label=\"BSS (symmetric)\")\n"
        "plt.tight_layout()\n"
        "plt.savefig(\"/tmp/lattice_graph.png\", dpi=110)\n"
        "plt.show()\n"
        "\n"
        "labeled = (y >= 0).sum()\n"
        "print(\"nodes:\", n, \"| labeled:\", labeled, \"| context nodes:\", n - labeled)"
    ),
    md(
        "## §4 — Flat structural features vs a 2-layer GNN\n"
        "\n"
        "**Features (never text, only structure):** popcount, content\n"
        "frequency (HSF), the three gate coverages `BSS(gate_p, node)`, and\n"
        "the general-lattice coverage `BSS(lattice, node)` — six numbers per\n"
        "node.\n"
        "\n"
        "**Two models, same features, same splits:**\n"
        "\n"
        "- **MLP**: features → 16 → 3 (flat baseline — the typed-head\n"
        "  discipline from notebook 07);\n"
        "- **GNN**: a 2-layer graph-convolution `H' = ReLU(Â H W)` over the\n"
        "  normalized symmetric BSS adjacency (self-loops included).\n"
        "\n"
        "**Two regimes:**\n"
        "\n"
        "- *semi-supervised*: 60/20/20 split over all labeled nodes;\n"
        "- *query transfer*: train on **documents only**, evaluate on **all\n"
        "  queries** — the no-pretraining way to ask \"which profile is\n"
        "  asking?\" when the queries were never in the training set.\n"
        "\n"
        "The GNN may use the graph (and test-node features through it) — that\n"
        "is exactly its claimed advantage."
    ),
    code(
        "from collections import Counter\n"
        "\n"
        "content = Counter(nd[2] for nd in nodes)\n"
        "X = np.zeros((n, 6))\n"
        "for i, (_, _, s) in enumerate(nodes):\n"
        "    X[i, 0] = s.bit_count()\n"
        "    X[i, 1] = content[s]\n"
        "    X[i, 2] = bss(gates[PROFILES[0]], s)\n"
        "    X[i, 3] = bss(gates[PROFILES[1]], s)\n"
        "    X[i, 4] = bss(gates[PROFILES[2]], s)\n"
        "    X[i, 5] = bss(lattice, s)\n"
        "\n"
        "Xmean = X.mean(axis=0, keepdims=True)\n"
        "Xstd = X.std(axis=0, keepdims=True) + 1e-8\n"
        "Xz = (X - Xmean) / Xstd\n"
        "\n"
        "# normalized symmetric adjacency with self-loops: Â = D^-1/2 (A+I) D^-1/2\n"
        "Ahat = A + np.eye(n)\n"
        "deg = Ahat.sum(axis=1)\n"
        "Dinv = np.diag(1.0 / np.sqrt(deg))\n"
        "A_norm = Dinv @ Ahat @ Dinv\n"
        "\n"
        "Xt = torch.tensor(Xz, dtype=torch.float32)\n"
        "At = torch.tensor(A_norm, dtype=torch.float32)\n"
        "yt = torch.tensor(y, dtype=torch.long)\n"
        "\n"
        "class MLP(nn.Module):\n"
        "    def __init__(self, d, h, c):\n"
        "        super().__init__()\n"
        "        self.w1 = nn.Parameter(torch.randn(d, h) * 0.1)\n"
        "        self.b1 = nn.Parameter(torch.zeros(h))\n"
        "        self.w2 = nn.Parameter(torch.randn(h, c) * 0.1)\n"
        "        self.b2 = nn.Parameter(torch.zeros(c))\n"
        "    def forward(self, x):\n"
        "        h = F.relu(x @ self.w1 + self.b1)\n"
        "        return h @ self.w2 + self.b2\n"
        "\n"
        "class GCN(nn.Module):\n"
        "    def __init__(self, d, h, c):\n"
        "        super().__init__()\n"
        "        self.w1 = nn.Parameter(torch.randn(d, h) * 0.1)\n"
        "        self.b1 = nn.Parameter(torch.zeros(h))\n"
        "        self.w2 = nn.Parameter(torch.randn(h, c) * 0.1)\n"
        "        self.b2 = nn.Parameter(torch.zeros(c))\n"
        "    def forward(self, x, a):\n"
        "        h = F.relu(a @ (x @ self.w1 + self.b1))\n"
        "        return a @ (h @ self.w2 + self.b2)\n"
        "\n"
        "def train_eval(model, gnn, train_mask, val_mask, test_mask, epochs=300, lr=0.03):\n"
        "    opt = torch.optim.Adam(model.parameters(), lr=lr)\n"
        "    best_val = -1\n"
        "    best_state = None\n"
        "    hist = []\n"
        "    for ep in range(epochs):\n"
        "        model.train()\n"
        "        opt.zero_grad()\n"
        "        out = model(Xt, At) if gnn else model(Xt)\n"
        "        loss = F.cross_entropy(out[train_mask], yt[train_mask])\n"
        "        loss.backward()\n"
        "        opt.step()\n"
        "        hist.append(float(loss.item()))\n"
        "        model.eval()\n"
        "        with torch.no_grad():\n"
        "            outv = model(Xt, At) if gnn else model(Xt)\n"
        "            vacc = (outv[val_mask].argmax(1) == yt[val_mask]).float().mean().item()\n"
        "        if vacc > best_val:\n"
        "            best_val = vacc\n"
        "            best_state = {k: v.clone() for k, v in model.state_dict().items()}\n"
        "    model.load_state_dict(best_state)\n"
        "    model.eval()\n"
        "    with torch.no_grad():\n"
        "        out = model(Xt, At) if gnn else model(Xt)\n"
        "        tacc = (out[test_mask].argmax(1) == yt[test_mask]).float().mean().item()\n"
        "    return tacc, best_val, hist\n"
        "\n"
        "print(\"models ready\")"
    ),
    code(
        "labeled_idx = np.where(y >= 0)[0]\n"
        "rng.shuffle(labeled_idx)\n"
        "tr_end = int(0.6 * len(labeled_idx))\n"
        "va_end = int(0.8 * len(labeled_idx))\n"
        "\n"
        "def mask(idx):\n"
        "    m = torch.zeros(n, dtype=torch.bool)\n"
        "    m[idx] = True\n"
        "    return m\n"
        "\n"
        "train_mask = mask(labeled_idx[:tr_end])\n"
        "val_mask   = mask(labeled_idx[tr_end:va_end])\n"
        "test_mask  = mask(labeled_idx[va_end:])\n"
        "\n"
        "results = {}\n"
        "for name, model, gnn in [(\"MLP\", MLP(6, 16, 3), False),\n"
        "                          (\"GNN\", GCN(6, 16, 3), True)]:\n"
        "    tacc, vacc, hist = train_eval(model, gnn, train_mask, val_mask, test_mask)\n"
        "    q = test_mask & torch.tensor([lbl.startswith(\"q_\") for lbl in labels])\n"
        "    model.eval()\n"
        "    with torch.no_grad():\n"
        "        out = model(Xt, At) if gnn else model(Xt)\n"
        "        qacc = (out[q].argmax(1) == yt[q]).float().mean().item() if q.sum() else float(\"nan\")\n"
        "    results[name] = (tacc, vacc, qacc, hist)\n"
        "    print(f\"{name:4s} semi-supervised: test acc {tacc:.3f} | val {vacc:.3f} | query-only {qacc:.3f}\")\n"
        "\n"
        "plt.figure(figsize=(9, 4))\n"
        "for name in results:\n"
        "    plt.plot(results[name][3], lw=1.2, label=name)\n"
        "plt.xlabel(\"epoch\")\n"
        "plt.ylabel(\"train loss\")\n"
        "plt.title(\"Training curves (same features, same split)\")\n"
        "plt.legend()\n"
        "plt.grid(alpha=0.25)\n"
        "plt.tight_layout()\n"
        "plt.savefig(\"/tmp/gnn_vs_mlp.png\", dpi=110)\n"
        "plt.show()"
    ),
    code(
        "# Query-transfer regime: train on every document, evaluate on every query.\n"
        "doc_idx = np.array([i for i in range(n) if y[i] >= 0 and not labels[i].startswith(\"q_\")])\n"
        "qry_idx = np.array([i for i in range(n) if y[i] >= 0 and labels[i].startswith(\"q_\")])\n"
        "rng.shuffle(doc_idx)\n"
        "vsplit = int(0.8 * len(doc_idx))\n"
        "\n"
        "print(\"query-transfer (train on docs, evaluate on all queries):\")\n"
        "for name, model, gnn in [(\"MLP\", MLP(6, 16, 3), False),\n"
        "                          (\"GNN\", GCN(6, 16, 3), True)]:\n"
        "    tacc, vacc, hist = train_eval(model, gnn, mask(doc_idx[:vsplit]),\n"
        "                                   mask(doc_idx[vsplit:]), mask(qry_idx))\n"
        "    print(f\"  {name:4s} query acc {tacc:.3f} | val {vacc:.3f}\")"
    ),
    md(
        "## §5 — What this says about a GNN for the EWM lattice\n"
        "\n"
        "- The **no-pretraining** mechanics need no model at all: the lattice\n"
        "  and the three gates grew from the stream as monotone bit unions,\n"
        "  and the query routing coordinates (`BSS(query, gate_p)`) are\n"
        "  already a working, interpretable classifier — the profiles are\n"
        "  visible in the graph's block structure before any learning.\n"
        "- The **MLP vs GNN** comparison is the notebook-08 discipline: if the\n"
        "  GNN wins, a graph readout earns its place as a learned companion\n"
        "  (a HF model behind the same typed daemon as `ewm-pagerank`); if it\n"
        "  ties, the lattice's local structural features are already very\n"
        "  strong and the graph adds little for *this* task — both are useful\n"
        "  findings.\n"
        "- The experiment is deliberately small and synthetic. The honest next\n"
        "  scale-up: real enterprise documents, more profiles, and the\n"
        "  **query-transfer regime** as the headline metric — recognizing the\n"
        "  issuing profile of never-seen queries from structure alone."
    ),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "ewm-nanolm",
            "language": "python",
            "name": "ewm-nanolm",
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.10",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

with open(NB_PATH, "w") as fh:
    json.dump(nb, fh, indent=1)
    fh.write("\n")
print("wrote", NB_PATH, "with", len(cells), "cells")
