#!/usr/bin/env python3
"""Build notebooks/22_typed_head_distill.ipynb (two-stage diagnosis)."""

import json

NB_PATH = "/home/alexmy/SGS/SGS_lib/fractal_manifold_gen2/ewm-laya-bonsai-lab/notebooks/07_typed_head_distill.ipynb"

md = lambda s: {"cell_type": "markdown", "metadata": {}, "source": s}
code = lambda s: {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": s,
}

cells = [
    md(
        "# 07 — Typed-head router: distilling the structural LLM into a tiny student\n"
        "\n"
        "The structural-router notebook (ewm-state-machine notebook 21) replaced Jev/Laya with a prompted local LLM\n"
        "(`StructuralLlmRouter`) that reads the lattice + ring state and returns\n"
        "a typed decision. This notebook distills that teacher into a **typed\n"
        "head** — a tiny MLP over a fixed-size feature vector — the same idea as\n"
        "Laya (non-autoregressive encoder + decision head), but trained on our\n"
        "own structural state.\n"
        "\n"
        "The run is a **two-stage diagnosis**, because the prompted teacher turns\n"
        "out to be heavily biased (almost always `llm_c`):\n"
        "\n"
        "1. collect teacher soft labels from a closed loop with\n"
        "   `structural=True`,\n"
        "2. train a **structural-only** head (`bss` + `drn` + `ring` + phase) —\n"
        "   and watch it collapse to the teacher's majority class,\n"
        "3. add a **query one-hot** (still no free text) and watch the head\n"
        "   recover the teacher's routing,\n"
        "4. plug the recovered student back into the loop behind the same\n"
        "   `DecisionRouter` seam and A/B it against the teacher and Jev-mock.\n"
        "\n"
        "The lesson is the deliverable: the distillation pipeline is correct,\n"
        "but a degenerate teacher makes the structural-only student a prior —\n"
        "text (here, the query identity) is what actually drives this teacher."
    ),
    code(
        "import os, sys, json\n"
        "\n"
        "# Same GPU pin as notebook 21: with PCI_BUS_ID on this machine the\n"
        "# Quadro M1200 is device 0 and the RTX 3060 is device 1.\n"
        "os.environ[\"CUDA_DEVICE_ORDER\"] = \"PCI_BUS_ID\"\n"
        "os.environ[\"CUDA_VISIBLE_DEVICES\"] = \"1\"\n"
        "os.environ.setdefault(\"HF_HUB_DISABLE_PROGRESS_BARS\", \"1\")\n"
        "\n"
        "import numpy as np\n"
        "import torch\n"
        "import torch.nn as nn\n"
        "\n"
        "EWM_SM = \"/home/alexmy/SGS/SGS_lib/fractal_manifold_gen2/ewm-state-machine\"\n"
        "sys.path.insert(0, EWM_SM)\n"
        "\n"
        "from trainer import (\n"
        "    DecisionRecord,\n"
        "    DecisionRouter,\n"
        "    EwmScene,\n"
        "    JevAdapter,\n"
        "    LlmAdapter,\n"
        "    StructuralLlmRouter,\n"
        "    run_open_loop,\n"
        "    run_jev_loop,\n"
        ")\n"
        "\n"
        "WORK = \"/home/alexmy/.cache/ewm-typed-head\"\n"
        "os.makedirs(WORK, exist_ok=True)\n"
        "ewm = EwmScene()\n"
        "print(\"torch sees:\", torch.cuda.get_device_name(0),\n"
        "      round(torch.cuda.get_device_properties(0).total_memory / 1e9, 1), \"GB\")\n"
        "print(\"work:\", WORK)"
    ),
    code(
        "QUERIES = [\n"
        "    \"What is the capital of France?\",                                    # trivial\n"
        "    \"Explain the intuition behind general relativity in three sentences.\",  # reasoned\n"
        "    \"Write a haiku about rain.\",                                          # creative\n"
        "    \"What is 17 * 24?\",                                                   # trivial\n"
        "    \"Compare supervised and unsupervised learning briefly.\",              # reasoned\n"
        "    \"What is the speed of light?\",                                        # trivial\n"
        "    \"Define entropy in simple words.\",                                    # short factual\n"
        "    \"Summarize the plot of Romeo and Juliet.\",                            # short factual\n"
        "]\n"
        "QUERY_INDEX = {q: i for i, q in enumerate(QUERIES)}\n"
        "\n"
        "adapter = LlmAdapter(max_new_tokens=32)\n"
        "teacher = StructuralLlmRouter(max_new_tokens=96)   # the prompted router = teacher\n"
        "jev     = JevAdapter(mock=True)\n"
        "\n"
        "print(\"adapter names:\", adapter.names)\n"
        "print(\"teacher mode:\", \"mock\" if teacher.mock else \"real\", \"|\", teacher.model_id)\n"
        "print(\"Jev mode:\", \"mock\" if jev.mock else \"real SDK\")"
    ),
    md("## §1 — Collect teacher soft labels (the distillation dataset)"),
    code(
        "open_result = run_open_loop(adapter, ewm, QUERIES, WORK, cycles=2, max_new_tokens=32)\n"
        "print(\"IICA:\", open_result.same_union, \"| BSS:\", open_result.M_ol.shape,\n"
        "      \"| period:\", open_result.period, \"(true 8)\")"
    ),
    code(
        "# Teacher closed loop = data collection. structural=True so every\n"
        "# routing_log entry carries the full lattice + ring state.\n"
        "teacher_result = run_jev_loop(\n"
        "    adapter, teacher, ewm, open_result, QUERIES, WORK, T=24, max_new_tokens=32,\n"
        "    structural=True, ingest_decision=True,\n"
        ")\n"
        "\n"
        "data = teacher_result.routing_log\n"
        "print()\n"
        "print(\"teacher decision distribution:\")\n"
        "for n in adapter.names:\n"
        "    print(f\"  {n:6s} {sum(1 for r in data if r['decision']['decision'] == n):2d} steps\")\n"
        "print(\"mean teacher confidence:\",\n"
        "      round(float(np.mean([r['decision']['confidence'] for r in data])), 4))\n"
        "\n"
        "with open(f\"{WORK}/distill_dataset.jsonl\", \"w\") as fh:\n"
        "    for r in data:\n"
        "        fh.write(json.dumps(r) + \"\\n\")\n"
        "print(\"saved:\", f\"{WORK}/distill_dataset.jsonl\", f\"({len(data)} labelled states)\")"
    ),
    md("## §2 — The typed-head student: structural-only vs + query identity"),
    code(
        "OPTION_ORDER = sorted(adapter.names)\n"
        "\n"
        "def structural_features(state):\n"
        "    \"\"\"bss (3) + drn (5) + ring (5) + phase (2) + step/16 (1) + bias (1) = 17.\"\"\"\n"
        "    bss  = state.get(\"bss\") or {}\n"
        "    drn  = state.get(\"drn\") or {}\n"
        "    ring = state.get(\"ring\") or {}\n"
        "    t = float(state.get(\"step\", 0))\n"
        "    ph = 2.0 * np.pi * t / 8.0\n"
        "    feats = [float(bss.get(n, 0.0)) for n in OPTION_ORDER]\n"
        "    feats += [float(drn.get(\"dp\", 0)), float(drn.get(\"rp\", 0)),\n"
        "              float(drn.get(\"np\", 0)), float(drn.get(\"ind1\", 0)),\n"
        "              float(drn.get(\"ind3\", 0))]\n"
        "    feats += [float(ring.get(\"residual\", 0)), float(ring.get(\"in_span\", False)),\n"
        "              float(ring.get(\"dim\", 0)), float(ring.get(\"rotation_count\", 0)),\n"
        "              float(ring.get(\"spill_first\", 0))]\n"
        "    feats += [np.sin(ph), np.cos(ph), t / 16.0, 1.0]\n"
        "    return np.asarray(feats, dtype=np.float32)\n"
        "\n"
        "def query_features(state):\n"
        "    \"\"\"One-hot of the query index (8) — identity, not free text.\"\"\"\n"
        "    q = str(state.get(\"query\", \"\"))\n"
        "    onehot = np.zeros(len(QUERIES), dtype=np.float32)\n"
        "    if q in QUERY_INDEX:\n"
        "        onehot[QUERY_INDEX[q]] = 1.0\n"
        "    return onehot\n"
        "\n"
        "def router_features(state, with_query=False):\n"
        "    f = structural_features(state)\n"
        "    return np.concatenate([f, query_features(state)]) if with_query else f\n"
        "\n"
        "class TypedHead(nn.Module):\n"
        "    def __init__(self, in_dim, n_options, hidden=32, dropout=0.1):\n"
        "        super().__init__()\n"
        "        self.net = nn.Sequential(\n"
        "            nn.Linear(in_dim, hidden), nn.ReLU(), nn.Dropout(dropout),\n"
        "            nn.Linear(hidden, hidden), nn.ReLU(), nn.Dropout(dropout),\n"
        "            nn.Linear(hidden, n_options),\n"
        "        )\n"
        "    def forward(self, x):\n"
        "        return self.net(x)\n"
        "\n"
        "X_struct = np.stack([router_features(r[\"state\"], with_query=False) for r in data])\n"
        "X_full   = np.stack([router_features(r[\"state\"], with_query=True)  for r in data])\n"
        "Y = np.stack([[r[\"decision\"][\"probabilities\"].get(n, 0.0)\n"
        "              for n in OPTION_ORDER] for r in data])\n"
        "print(\"structural feature dim:\", X_struct.shape[1], \"| full (with query) dim:\", X_full.shape[1])\n"
        "print(\"labelled states:\", len(X_struct))\n"
        "print(\"teacher label histogram:\", np.round(Y.sum(axis=0), 1))"
    ),
    code(
        "def train_head(X, Y, seed=0, epochs=1500):\n"
        "    rng = np.random.default_rng(seed)\n"
        "    # Stratified split: keep every teacher class in both train and test\n"
        "    # (a plain random split can strand the minority class in test).\n"
        "    y_cls = np.argmax(Y, axis=1)\n"
        "    tr, te = [], []\n"
        "    for c in np.unique(y_cls):\n"
        "        idx_c = np.where(y_cls == c)[0]\n"
        "        rng.shuffle(idx_c)\n"
        "        n_tr_c = max(1, int(0.8 * len(idx_c)))\n"
        "        tr += list(idx_c[:n_tr_c])\n"
        "        te += list(idx_c[n_tr_c:])\n"
        "    tr, te = np.array(tr), np.array(te)\n"
        "    mu, sd = X[tr].mean(axis=0), X[tr].std(axis=0) + 1e-9\n"
        "    Xs = (X - mu) / sd\n"
        "    torch.manual_seed(seed)\n"
        "    model = TypedHead(X.shape[1], len(OPTION_ORDER))\n"
        "    opt = torch.optim.Adam(model.parameters(), lr=2e-3, weight_decay=1e-3)\n"
        "    Xtr = torch.tensor(Xs[tr]); Ytr = torch.tensor(Y[tr])\n"
        "    Xte = torch.tensor(Xs[te]); Yte = torch.tensor(Y[te])\n"
        "    losses = []\n"
        "    for _ in range(epochs):\n"
        "        opt.zero_grad()\n"
        "        logp = torch.log_softmax(model(Xtr), dim=1)\n"
        "        loss = torch.mean(torch.sum(-Ytr * logp, dim=1))   # CE with soft teacher targets\n"
        "        loss.backward()\n"
        "        opt.step()\n"
        "        losses.append(float(loss))\n"
        "    with torch.no_grad():\n"
        "        p_te = torch.softmax(model(Xte), dim=1).numpy()\n"
        "    acc = float(np.mean(np.argmax(p_te, axis=1) == np.argmax(Y[te], axis=1)))\n"
        "    kl = float(np.mean(np.sum(Y[te] * (np.log(Y[te] + 1e-9) - np.log(p_te + 1e-9)), axis=1)))\n"
        "    return model, mu, sd, losses, te, p_te, acc, kl\n"
        "\n"
        "# Stage 1: structural-only student.\n"
        "head_struct, mu_s, sd_s, losses_s, te_s, p_s, acc_s, kl_s = train_head(X_struct, Y)\n"
        "print(f\"structural-only : test argmax-acc {acc_s:.2f}  | test KL {kl_s:.4f}\")\n"
        "\n"
        "# Stage 2: + query identity.\n"
        "head_full, mu_f, sd_f, losses_f, te_f, p_f, acc_f, kl_f = train_head(X_full, Y)\n"
        "print(f\"+ query identity : test argmax-acc {acc_f:.2f}  | test KL {kl_f:.4f}\")\n"
        "\n"
        "print()\n"
        "print(\"held-out teacher vs head (with query identity):\")\n"
        "for i in range(len(te_f)):\n"
        "    print(f\"  state {te_f[i]:2d}: teacher {np.round(Y[te_f[i]], 2)}  head {np.round(p_f[i], 2)}\")"
    ),
    code(
        "%matplotlib inline\n"
        "import matplotlib.pyplot as plt\n"
        "\n"
        "fig, axes = plt.subplots(1, 2, figsize=(11, 4))\n"
        "axes[0].plot(losses_s, lw=1.0, alpha=0.8, color=\"tab:red\", label=\"structural-only\")\n"
        "axes[0].plot(losses_f, lw=1.0, alpha=0.8, color=\"tab:blue\", label=\"+ query identity\")\n"
        "axes[0].set_xlabel(\"epoch\")\n"
        "axes[0].set_ylabel(\"CE loss (soft teacher)\")\n"
        "axes[0].set_title(\"typed-head distillation\")\n"
        "axes[0].legend(fontsize=8)\n"
        "axes[0].grid(alpha=0.25)\n"
        "\n"
        "bar_x = np.arange(len(te_f))\n"
        "width = 0.32\n"
        "for j, n in enumerate(OPTION_ORDER):\n"
        "    axes[1].bar(bar_x + (j - 1) * width, Y[te_f][:, j], width, label=f\"teacher {n}\")\n"
        "for j, n in enumerate(OPTION_ORDER):\n"
        "    axes[1].bar(bar_x + (j - 1) * width, p_f[:, j], width, alpha=0.45, label=f\"head {n}\")\n"
        "axes[1].set_xticks(bar_x, [str(i) for i in te_f])\n"
        "axes[1].set_xlabel(\"held-out state index\")\n"
        "axes[1].set_ylabel(\"P(option)\")\n"
        "axes[1].set_title(\"teacher vs distilled head (+ query identity)\")\n"
        "axes[1].legend(fontsize=6, ncol=2)\n"
        "axes[1].grid(alpha=0.25)\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.savefig(f\"{WORK}/typed_head_distill.png\", dpi=110)\n"
        "plt.show()"
    ),
    md("## §3 — Plug the recovered student into the loop, then A/B"),
    code(
        "class TypedHeadRouter(DecisionRouter):\n"
        "    \"\"\"The distilled student behind the same DecisionRouter seam.\"\"\"\n"
        "    def __init__(self, model, feature_fn, option_order, mu, sd):\n"
        "        self.model = model\n"
        "        self.feature_fn = feature_fn\n"
        "        self.option_order = list(option_order)\n"
        "        self.mu = mu\n"
        "        self.sd = sd\n"
        "\n"
        "    def route(self, state, options, instructions, extra_noul=None):\n"
        "        x = (self.feature_fn(state) - self.mu) / self.sd\n"
        "        with torch.no_grad():\n"
        "            logits = self.model(torch.tensor(x).unsqueeze(0))[0]\n"
        "        p = torch.softmax(logits, dim=0).numpy()\n"
        "        probs = {n: float(p[i]) for i, n in enumerate(self.option_order)}\n"
        "        decision = max(probs, key=probs.get)\n"
        "        return DecisionRecord(\n"
        "            decision=decision,\n"
        "            confidence=float(probs[decision]),\n"
        "            probabilities=probs,\n"
        "            decision_type=\"route_query\",\n"
        "            aux={},\n"
        "            model=\"typed-head-distill\",\n"
        "            mock=False,\n"
        "        )\n"
        "\n"
        "# deploy the stage-2 student (structural + query identity).\n"
        "head_router = TypedHeadRouter(\n"
        "    head_full, lambda s: router_features(s, with_query=True), OPTION_ORDER, mu_f, sd_f\n"
        ")\n"
        "\n"
        "head_result = run_jev_loop(\n"
        "    adapter, head_router, ewm, open_result, QUERIES, WORK, T=8, max_new_tokens=32,\n"
        "    structural=True, ingest_decision=True,\n"
        ")\n"
        "print()\n"
        "print(\"typed-head decision distribution:\")\n"
        "for n in adapter.names:\n"
        "    print(f\"  {n:6s} {sum(1 for d in head_result.decision_log if d.decision == n):2d} steps\")\n"
        "print(\"mean confidence:\",\n"
        "      round(float(np.mean([d.confidence for d in head_result.decision_log])), 4))\n"
        "\n"
        "torch.save({\"model\": head_full.state_dict(), \"mu\": mu_f, \"sd\": sd_f,\n"
        "            \"option_order\": OPTION_ORDER, \"feature_dim\": X_full.shape[1]},\n"
        "           f\"{WORK}/typed_head.pt\")\n"
        "print(\"saved:\", f\"{WORK}/typed_head.pt\")"
    ),
    code(
        "jev_result = run_jev_loop(\n"
        "    adapter, jev, ewm, open_result, QUERIES, WORK, T=8, max_new_tokens=32,\n"
        "    ingest_decision=True,\n"
        ")\n"
        "\n"
        "# teacher row comes from the 24-step data-collection run; head and jev run 8.\n"
        "rows = [(\"teacher-qwen\", teacher_result), (\"typed-head\", head_result), (\"jev-mock\", jev_result)]\n"
        "print(f\"{'router':14s} {'choice distribution':30s} {'gated':>6s} {'mean conf':>10s}\")\n"
        "for label, r in rows:\n"
        "    ds = r.decision_log\n"
        "    dist = \", \".join(f\"{n}:{sum(1 for d in ds if d.decision == n)}\" for n in adapter.names)\n"
        "    print(f\"{label:14s} {dist:30s} {sum(r.gated_log):6d} \"\n"
        "          f\"{float(np.mean([d.confidence for d in ds])):10.4f}\")"
    ),
    md(
        "## Summary\n"
        "\n"
        "- **Pipeline works end-to-end**: teacher loop with `structural=True` →\n"
        "  soft-label dataset → tiny MLP distilled with cross-entropy → deployed\n"
        "  behind the same `DecisionRouter` seam → A/B in the loop. The student\n"
        "  is a single CPU forward pass on a ≤25-dim vector (no GPU, no API).\n"
        "- **Structural-only is not enough**: the prompted teacher is degenerate\n"
        "  (21/24 `llm_c`), so the structural-only head collapses to that prior.\n"
        "  Adding the **query identity** recovers the teacher's routing — the\n"
        "  teacher's decisions are driven by the query, not by the lattice.\n"
        "- **Artifacts**: `distill_dataset.jsonl` (behavioural-cloning dataset),\n"
        "  `typed_head.pt` (the recovered student).\n"
        "\n"
        "This is exactly the kind of failure mode a distillation pipeline must\n"
        "surface. Next steps: (1) a less degenerate teacher (nb17-style prompt\n"
        "A/B, or temperature sampling to spread the soft labels); (2) more\n"
        "diverse query banks and longer logs; (3) query/option *text*\n"
        "embeddings instead of a one-hot; (4) reward fine-tuning of the head\n"
        "with loop surprise instead of pure distillation; (5) port the head to\n"
        "a Rust/candle daemon like Laya."
    ),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "ewm-nanolm",
            "language": "python",
            "name": "ewm-nanolm",
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.10",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

with open(NB_PATH, "w") as fh:
    json.dump(nb, fh, indent=1)
    fh.write("\n")
print("wrote", NB_PATH, "with", len(cells), "cells")
