#!/usr/bin/env python3
"""Build notebooks/14_slot_prototype.ipynb — the minimal bonsai-ewm slot.

The Lombardi thesis made concrete: the same scripted model behind two
different harnesses (verbose vs terse phrasing policy) behaves like two
different agents. The harness talks to the real ewm-pagerank daemon over
JSON-lines: profile -> prompt -> encodings -> lattice ops -> typed context
-> model -> tool request -> result phrased back through the slot.
"""

import json

NB_PATH = "/home/alexmy/SGS/SGS_lib/fractal_manifold_gen2/ewm-laya-bonsai-lab/notebooks/14_slot_prototype.ipynb"

md = lambda s: {"cell_type": "markdown", "metadata": {}, "source": s}
code = lambda s: {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": s,
}

cells = [
    md(
        "# 14 — The slot: a minimal `bonsai-ewm` harness loop\n"
        "\n"
        "> \"Which shapes count as a tool request, how a tool's result is\n"
        "> phrased when it goes back through the slot, what the model is told\n"
        "> about the tools it has… all of this is decided by the person at the\n"
        "> slot, and all of it changes what comes out.\"\n"
        "> — Enzo Lombardi, *Writing an Agent Harness in Rust*\n"
        "\n"
        "This notebook makes that claim concrete with a **minimal slot**: a\n"
        "Python harness that speaks to the real `ewm-pagerank` daemon over\n"
        "JSON-lines. One turn through the slot:\n"
        "\n"
        "```text\n"
        "   profile ──► prompt ──► host LLM ──► encodings ──► query HLLSet\n"
        "                                                    │\n"
        "   harness (THE SLOT)                              │\n"
        "     assemble context (phrasing policy) ◄──────────┘\n"
        "     model responds with a tool-request shape\n"
        "     harness executes the tool (daemon op)\n"
        "     harness phrases the result back through the slot\n"
        "     … until the model emits the answer shape\n"
        "```\n"
        "\n"
        "The model is a **scripted policy** (no weights — the point is the\n"
        "harness). Two harnesses around that same model: **verbose** (the\n"
        "harness eagerly includes the bases) and **terse** (it does not). The\n"
        "same model, the same prompt, the same lattice — different tool-call\n"
        "sequences and different final answers. That is the quote, runnable."
    ),
    code(
        "import json, os, re, subprocess, sys\n"
        "\n"
        "import mmh3\n"
        "import numpy as np\n"
        "\n"
        "BITS_PER_REG = 32\n"
        "P = 10\n"
        "\n"
        "def frame_set(tokens, p=P):\n"
        "    s = 0\n"
        "    m = 1 << p\n"
        "    for t in tokens:\n"
        "        for seed in (0, 1, 2):\n"
        "            h = mmh3.hash64(t.encode(), seed=seed, signed=False)[0]\n"
        "            reg = h & (m - 1)\n"
        "            rem = h >> p\n"
        "            tz = 31 if rem == 0 else min((rem & -rem).bit_length() - 1, 31)\n"
        "            s |= 1 << (reg * BITS_PER_REG + tz)\n"
        "    return s\n"
        "\n"
        "def bss(a, b):\n"
        "    pb = b.bit_count()\n"
        "    return (a & b).bit_count() / pb if pb else 0.0\n"
        "\n"
        "PROFILES = [\"acme-finance\", \"medco-clinical\", \"ops-logistics\"]\n"
        "DOMAIN_WORDS = {\n"
        "    \"acme-finance\": [\"market\",\"equity\",\"bond\",\"risk\",\"portfolio\",\"dividend\",\"yield\",\n"
        "                      \"capital\",\"audit\",\"ledger\",\"valuation\",\"liquidity\",\"hedge\",\n"
        "                      \"settlement\",\"margin\",\"revenue\",\"expense\",\"asset\",\"liability\",\n"
        "                      \"deposit\",\"forecast\",\"budget\"],\n"
        "    \"medco-clinical\": [\"patient\",\"trial\",\"dosage\",\"symptom\",\"diagnosis\",\"therapy\",\n"
        "                        \"efficacy\",\"placebo\",\"cohort\",\"regimen\",\"adverse\",\"protocol\",\n"
        "                        \"enrollment\",\"endpoint\",\"biomarker\",\"dose\",\"arm\",\"screening\",\n"
        "                        \"followup\",\"outcome\",\"consent\",\"monitor\"],\n"
        "    \"ops-logistics\": [\"shipment\",\"warehouse\",\"inventory\",\"route\",\"dispatch\",\"carrier\",\n"
        "                       \"pallet\",\"tracking\",\"freight\",\"schedule\",\"capacity\",\"dock\",\n"
        "                       \"fleet\",\"manifest\",\"handling\",\"leadtime\",\"backlog\",\"delivery\",\n"
        "                       \"pickup\",\"transit\",\"cargo\",\"distribution\"],\n"
        "}\n"
        "SHARED = [\"the\",\"of\",\"report\",\"update\",\"review\",\"summary\",\"data\",\"system\",\n"
        "          \"process\",\"request\",\"note\",\"status\",\"current\",\"check\",\"record\",\"entry\"]\n"
        "\n"
        "DEMO = \"/tmp/ewm-slot-demo\"\n"
        "os.makedirs(DEMO, exist_ok=True)\n"
        "\n"
        "# The profile gates are the domain codebooks (the tool surface).\n"
        "gates = [{\"name\": p, \"tokens\": DOMAIN_WORDS[p]} for p in PROFILES]\n"
        "with open(f\"{DEMO}/frame.json\", \"w\") as fh:\n"
        "    json.dump({\"dimensions\": gates}, fh)\n"
        "\n"
        "rng = np.random.default_rng(7)\n"
        "frames = []\n"
        "for i in range(100):\n"
        "    p = PROFILES[i % 3]\n"
        "    toks = [str(rng.choice(DOMAIN_WORDS[p])) if rng.random() < 0.72\n"
        "            else str(rng.choice(SHARED)) for _ in range(int(rng.integers(80, 121)))]\n"
        "    frames.append({\"id\": f\"doc{i:03d}\", \"tokens\": toks})\n"
        "\n"
        "PROMPTS = {\n"
        "    \"acme-finance\": [\"equity exposure report\", \"bond yield forecast update\",\n"
        "                      \"quarterly revenue audit summary\", \"portfolio risk review status\"],\n"
        "    \"medco-clinical\": [\"patient trial enrollment status\", \"dosage regimen review\",\n"
        "                        \"symptom diagnosis report\", \"therapy efficacy update\"],\n"
        "    \"ops-logistics\": [\"shipment warehouse status\", \"inventory route update\",\n"
        "                       \"dispatch carrier report\", \"pallet tracking summary\"],\n"
        "}\n"
        "\n"
        "# Queries are prompts converted by the (simulated) host LLM encoder.\n"
        "QUERIES = []\n"
        "for p in PROFILES:\n"
        "    for q in range(4):\n"
        "        toks = PROMPTS[p][q].split()\n"
        "        QUERIES.append((f\"q_{p}_{q}\", p, PROMPTS[p][q], toks))\n"
        "        frames.append({\"id\": f\"q_{p}_{q}\", \"tokens\": toks})\n"
        "\n"
        "with open(f\"{DEMO}/frames.jsonl\", \"w\") as fh:\n"
        "    for f in frames:\n"
        "        fh.write(json.dumps(f) + \"\\n\")\n"
        "\n"
        "print(\"frames:\", len(frames), \"| gates:\", [g[\"name\"] for g in gates])\n"
        "print(\"queries:\", [q[0] for q in QUERIES])\n"
        "print(\"demo dir:\", DEMO)"
    ),
    code(
        "class PagerankClient:\n"
        "    \"\"\"The harness's handle on the ewm-pagerank daemon — JSON-lines on\n"
        "    stdin/stdout, exactly the Laya surface.\"\"\"\n"
        "\n"
        "    def __init__(self, bin_path):\n"
        "        self.proc = subprocess.Popen(\n"
        "            [bin_path, \"serve\"],\n"
        "            stdin=subprocess.PIPE, stdout=subprocess.PIPE,\n"
        "            stderr=subprocess.PIPE, text=True,\n"
        "        )\n"
        "        self._req = 0\n"
        "\n"
        "    def _send(self, req):\n"
        "        self._req += 1\n"
        "        req[\"id\"] = self._req\n"
        "        self.proc.stdin.write(json.dumps(req) + \"\\n\")\n"
        "        self.proc.stdin.flush()\n"
        "        line = self.proc.stdout.readline()\n"
        "        return json.loads(line)\n"
        "\n"
        "    def load(self, frames_path, frame_path=None):\n"
        "        req = {\"op\": \"load\", \"frames\": frames_path}\n"
        "        if frame_path:\n"
        "            req[\"frame\"] = frame_path\n"
        "        return self._send(req)\n"
        "\n"
        "    def bases(self, query, top=4):\n"
        "        resp = self._send({\"op\": \"bases\", \"query\": query, \"top\": top})\n"
        "        return resp[\"response\"][\"answers\"][\"bases\"]\n"
        "\n"
        "    def profile(self, profile_id, gates, top=3):\n"
        "        resp = self._send({\"op\": \"profile\", \"profile\": profile_id,\n"
        "                           \"gates\": gates, \"top\": top})\n"
        "        return resp[\"response\"][\"answers\"][\"profile\"]\n"
        "\n"
        "    def close(self):\n"
        "        if self.proc.poll() is None:\n"
        "            self.proc.stdin.close()\n"
        "            self.proc.terminate()\n"
        "            self.proc.wait(timeout=5)\n"
        "\n"
        "BIN = \"/home/alexmy/SGS/SGS_lib/fractal_manifold_gen2/ewm-emdm/target/release/ewm-pagerank\"\n"
        "assert os.path.exists(BIN), f\"build ewm-pagerank first (missing {BIN})\"\n"
        "\n"
        "client = PagerankClient(BIN)\n"
        "load_resp = client.load(f\"{DEMO}/frames.jsonl\", f\"{DEMO}/frame.json\")\n"
        "print(\"daemon loaded:\", load_resp[\"response\"].get(\"loaded\"),\n"
        "      \"|\", load_resp[\"response\"].get(\"usage\"))"
    ),
    md(
        "## §1 — The slot, one turn at a time\n"
        "\n"
        "The harness assembles the **context** (the phrasing policy decides\n"
        "what the model is told), the model emits a **tool-request shape**, the\n"
        "harness executes it against the daemon and phrases the result back\n"
        "through the slot. Valid tool shapes in this prototype:\n"
        "\n"
        "- `{\"tool\": \"bases\", \"query\": \"<label>\"}` — ask what covers the query;\n"
        "- `{\"tool\": \"profile_summary\"}` — ask for the profile's top-k summaries;\n"
        "- `{\"tool\": \"answer\", \"text\": \"…\"}` — the final shape.\n"
        "\n"
        "Anything else is **not a tool request** and the harness ignores it —\n"
        "that filtering is itself a slot decision."
    ),
    code(
        "class ScriptedModel:\n"
        "    \"\"\"A deterministic policy with no weights. It answers when the\n"
        "    harness tells it the bases; otherwise it asks for them.\"\"\"\n"
        "\n"
        "    def respond(self, context, query_label):\n"
        "        if \"bases:\" in context:\n"
        "            m = re.search(r\"bases:\\n\\s*-\\s*(\\S+)\\s+\\(coverage=([0-9.]+)\", context)\n"
        "            if m:\n"
        "                return {\"tool\": \"answer\",\n"
        "                        \"text\": f\"top base is {m.group(1)} (coverage {m.group(2)})\"}\n"
        "            return {\"tool\": \"answer\", \"text\": \"no clear base\"}\n"
        "        return {\"tool\": \"bases\", \"query\": query_label}\n"
        "\n"
        "model = ScriptedModel()\n"
        "\n"
        "def phrase_bases(rec):\n"
        "    \"\"\"The harness's phrasing of a bases tool result — references, not prose.\"\"\"\n"
        "    lines = [f\"- {r['reference']} (coverage={r['score']:.2f}, h:{r['content_key'][2:8]}…)\"\n"
        "             for r in rec[\"ranking\"]]\n"
        "    return \"bases:\\n\" + \"\\n\".join(lines)\n"
        "\n"
        "def phrase_profile(rec):\n"
        "    lines = [f\"- {s['reference']} (pr={s['page_rank']:.4f}, \"\n"
        "             f\"gate_coverage={ {k: round(v,2) for k,v in s['gate_coverage'].items()} })\"\n"
        "             for s in rec[\"top_k\"]]\n"
        "    return \"profile_summary:\\n\" + \"\\n\".join(lines)\n"
        "\n"
        "def assemble_context(client, profile, query_label, policy):\n"
        "    \"\"\"The person-at-the-slot decision: what the model is told.\"\"\"\n"
        "    q_tokens = next(t for l, _, _, t in QUERIES if l == query_label)\n"
        "    q_set = frame_set(q_tokens)\n"
        "    gate_sets = {g[\"name\"]: frame_set(g[\"tokens\"]) for g in gates}\n"
        "    gate_cov = {name: round(bss(gs, q_set), 2) for name, gs in gate_sets.items()}\n"
        "    lines = [\n"
        "        f\"Query: {query_label} (issued by profile {profile})\",\n"
        "        \"Profile gates: \" + \", \".join(g[\"name\"] for g in gates),\n"
        "        \"Gate coverage of the query: \" + \", \".join(\n"
        "            f\"{k}={v:.2f}\" for k, v in sorted(gate_cov.items())),\n"
        "    ]\n"
        "    if policy == \"verbose\":\n"
        "        rec = client.bases(query_label, top=4)\n"
        "        lines.append(phrase_bases(rec))\n"
        "    return \"\\n\".join(lines)\n"
        "\n"
        "def run_turn(client, profile, query_label, policy, max_tools=3):\n"
        "    \"\"\"One full slot turn: context -> model -> tool -> phrased result…\"\"\"\n"
        "    trace = []\n"
        "    context = assemble_context(client, profile, query_label, policy)\n"
        "    trace.append((\"context\", context))\n"
        "    for _ in range(max_tools):\n"
        "        req = model.respond(context, query_label)\n"
        "        trace.append((\"model\", req))\n"
        "        if req[\"tool\"] == \"answer\":\n"
        "            return trace\n"
        "        if req[\"tool\"] == \"bases\":\n"
        "            rec = client.bases(req[\"query\"], top=4)\n"
        "            phrased = phrase_bases(rec)\n"
        "            context += \"\\n[slot] tool result: \" + phrased\n"
        "            trace.append((\"slot\", phrased))\n"
        "        elif req[\"tool\"] == \"profile_summary\":\n"
        "            rec = client.profile(profile, gates, top=3)\n"
        "            phrased = phrase_profile(rec)\n"
        "            context += \"\\n[slot] tool result: \" + phrased\n"
        "            trace.append((\"slot\", phrased))\n"
        "        else:\n"
        "            trace.append((\"slot\", \"ignored (not a valid tool shape)\"))\n"
        "    return trace\n"
        "\n"
        "print(\"slot machinery ready\")"
    ),
    md("## §2 — Verbose harness: the model is told the bases up front"),
    code(
        "q_label, q_profile, q_prompt, q_toks = QUERIES[0]\n"
        "print(\"prompt:\", q_prompt, \"| profile:\", q_profile, \"| query:\", q_label)\n"
        "print(\"=\" * 70)\n"
        "trace_v = run_turn(client, q_profile, q_label, policy=\"verbose\")\n"
        "for kind, payload in trace_v:\n"
        "    if kind == \"context\":\n"
        "        print(\"[slot] context assembled:\\n\" + payload)\n"
        "    elif kind == \"model\":\n"
        "        print(\"[model] tool request:\", json.dumps(payload))\n"
        "    else:\n"
        "        print(\"[slot] phrased result: \" + payload.replace(chr(10), \" | \"))\n"
        "print(\"=\" * 70)\n"
        "print(\"turns:\", sum(1 for k, _ in trace_v if k == \"model\"),\n"
        "      \"| tool calls:\", sum(1 for k, _ in trace_v if k == \"slot\"))"
    ),
    md("## §3 — Terse harness: the same model is not told the bases"),
    code(
        "print(\"prompt:\", q_prompt, \"| profile:\", q_profile, \"| query:\", q_label)\n"
        "print(\"=\" * 70)\n"
        "trace_t = run_turn(client, q_profile, q_label, policy=\"terse\")\n"
        "for kind, payload in trace_t:\n"
        "    if kind == \"context\":\n"
        "        print(\"[slot] context assembled:\\n\" + payload)\n"
        "    elif kind == \"model\":\n"
        "        print(\"[model] tool request:\", json.dumps(payload))\n"
        "    else:\n"
        "        print(\"[slot] phrased result: \" + payload.replace(chr(10), \" | \"))\n"
        "print(\"=\" * 70)\n"
        "print(\"turns:\", sum(1 for k, _ in trace_t if k == \"model\"),\n"
        "      \"| tool calls:\", sum(1 for k, _ in trace_t if k == \"slot\"))"
    ),
    md(
        "## §4 — Same model, same prompt, same lattice: two harnesses, two agents\n"
        "\n"
        "The scripted model has no weights — every difference between the two\n"
        "runs is a **harness decision**: the verbose harness told the model the\n"
        "bases, so it answered in one step; the terse harness withheld them, so\n"
        "the model had to *ask* for the tool, the harness executed it and\n"
        "phrased the result back. Same weights (none!), different agents."
    ),
    code(
        "def summarize(trace):\n"
        "    model_steps = [p for k, p in trace if k == \"model\"]\n"
        "    tool_calls = [p for k, p in trace if k == \"slot\" and isinstance(p, str)]\n"
        "    final = model_steps[-1] if model_steps else {}\n"
        "    return {\n"
        "        \"model_steps\": [m[\"tool\"] for m in model_steps],\n"
        "        \"tool_calls\": len(tool_calls),\n"
        "        \"final\": final.get(\"text\", \"\"),\n"
        "    }\n"
        "\n"
        "sv = summarize(trace_v)\n"
        "st = summarize(trace_t)\n"
        "print(f\"{'harness':10s} {'model steps':18s} {'tool calls':>10s}  final answer\")\n"
        "print(f\"{'verbose':10s} {str(sv['model_steps']):18s} {sv['tool_calls']:>10d}  {sv['final']}\")\n"
        "print(f\"{'terse':10s} {str(st['model_steps']):18s} {st['tool_calls']:>10d}  {st['final']}\")\n"
        "\n"
        "client.close()\n"
        "print(\"\\ndaemon closed\")"
    ),
    md(
        "## Summary\n"
        "\n"
        "- The **slot is the agent**: profile → prompt → encodings → lattice ops\n"
        "  (`profile`, `bases`) → typed context → model → tool request → result\n"
        "  phrased back. Every step in that chain is a harness decision.\n"
        "- The **daemon is the tool surface**: `rank`/`related`/`bases`/`profile`\n"
        "  are the only shapes that count as tool requests; the harness decides\n"
        "  which to expose to the model and how to phrase their results.\n"
        "- Two harnesses around the same model produced different tool-call\n"
        "  sequences and different final answers — the Lombardi quote,\n"
        "  executed.\n"
        "- Production shape (the EMDM phase): replace the scripted model with a\n"
        "  real host LLM behind the `DecisionRouter` seam, replace the simulated\n"
        "  encoder with the host LLM's tokenizer, and persist profiles in the\n"
        "  `gates/` store section. The slot loop stays exactly this shape."
    ),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "ewm-nanolm",
            "language": "python",
            "name": "ewm-nanolm",
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.10",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

with open(NB_PATH, "w") as fh:
    json.dump(nb, fh, indent=1)
    fh.write("\n")
print("wrote", NB_PATH, "with", len(cells), "cells")
